# Generated by Django 3.2.9 on 2021-12-07 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reklama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('image_1', models.ImageField(upload_to='')),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='newsmode',
            old_name='image',
            new_name='image_1',
        ),
        migrations.AddField(
            model_name='categorymode',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='newsmode',
            name='author',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newsmode',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='newsmode',
            name='image_3',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='newsmode',
            name='telegram_bot',
            field=models.BooleanField(default=False),
        ),
    ]
