# Generated by Django 3.2.9 on 2021-12-13 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_newsmode_actual'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsmode',
            name='text',
        ),
    ]
