# Generated by Django 3.2.9 on 2021-12-13 18:44

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_remove_newsmode_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsmode',
            name='text',
            field=ckeditor.fields.RichTextField(default=1),
            preserve_default=False,
        ),
    ]
