# Generated by Django 3.2.9 on 2021-12-14 18:12

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reklama',
            name='image_1',
        ),
        migrations.AddField(
            model_name='contact',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Faolmi'),
        ),
        migrations.AddField(
            model_name='reklama',
            name='image',
            field=models.ImageField(default=1, upload_to='', verbose_name='Rasmi'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reklama',
            name='url',
            field=models.URLField(default=1, verbose_name='Veb-manzili'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='categorymode',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Faolligi'),
        ),
        migrations.AlterField(
            model_name='categorymode',
            name='ctg_slug',
            field=models.CharField(max_length=50, verbose_name='Kategoriya slugi'),
        ),
        migrations.AlterField(
            model_name='categorymode',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Nomi'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Elektron pochtasi'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='first_name',
            field=models.CharField(max_length=200, verbose_name='Ismi'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone_number',
            field=models.CharField(max_length=200, verbose_name='Telefon raqami'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='Xabar'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Vaqti'),
        ),
        migrations.AlterField(
            model_name='newsmode',
            name='actual',
            field=models.BooleanField(default=False, verbose_name='Dolzarbmi'),
        ),
        migrations.AlterField(
            model_name='newsmode',
            name='author',
            field=models.CharField(max_length=200, verbose_name='Yozuvchi ismi'),
        ),
        migrations.AlterField(
            model_name='newsmode',
            name='ctg',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.categorymode', verbose_name='Kategoriya'),
        ),
        migrations.AlterField(
            model_name='newsmode',
            name='image_1',
            field=models.ImageField(upload_to='', verbose_name='Birinchi rasm'),
        ),
        migrations.AlterField(
            model_name='newsmode',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Ikkinchi rasm'),
        ),
        migrations.AlterField(
            model_name='newsmode',
            name='image_3',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Uchnchi rasm'),
        ),
        migrations.AlterField(
            model_name='newsmode',
            name='main',
            field=models.BooleanField(default=False, verbose_name='Asosiymi'),
        ),
        migrations.AlterField(
            model_name='newsmode',
            name='telegram_bot',
            field=models.BooleanField(default=False, verbose_name='Telegramga kanalga yuborilsinmi'),
        ),
        migrations.AlterField(
            model_name='newsmode',
            name='text',
            field=ckeditor.fields.RichTextField(verbose_name='Matn'),
        ),
        migrations.AlterField(
            model_name='newsmode',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Sarlavha'),
        ),
        migrations.AlterField(
            model_name='reklama',
            name='text',
            field=models.CharField(max_length=200, verbose_name='Nomi'),
        ),
        migrations.AlterField(
            model_name='reklama',
            name='time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Qo`yilgan vaqt'),
        ),
    ]
