# Generated by Django 3.2.9 on 2021-12-14 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_auto_20211214_2312'),
    ]

    operations = [
        migrations.AddField(
            model_name='reklama',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Faolmi'),
        ),
    ]
